variables:
  WORKDIR: "${CI_PROJECT_DIR}"

image:
  name: hashicorp/packer
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

stages:
  - validate
  - deploy

packer-validate-mysql:
  stage: validate
  script:
    - echo "packer validate mysql..."

    - cd mysql
    
    - packer validate  build.json
  
  only:
    - main
    - test

packer-validate-nginx:
  stage: validate
  script:
    - echo "packer validate nginx..."
   
    - cd nginix 
   
    - packer validate  build.json
  
  only:
    - main
    - test

packer-build-mysql:
  stage: deploy
  script:
     - echo "packer validate mysql..."

     - cd mysql
    
     - packer build -force build.json
  only:
    - main
    - tags
  when: manual

packer-build-nginx:
  stage: deploy
  script:
     - echo "packer validate mysql..."

     - cd mysql
    
     - packer build -force build.json
  only:
    - main
    - tags
  when: manual
