variables:
  WORKDIR: "${CI_PROJECT_DIR}"
  OS_PATH: ""

image:
  name: hashicorp/packer
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

stages:
  - validate
  - deploy

packer-validate:
  stage: validate

  script:
    - echo "packer validate ... "
    - packer validate "$WORKDIR/$OS_PATH"  .

  only:
    - main
    - test

mysql:
    extends: packer-validate
    variables:
        ospath: "$WORKDIR/mysql/"  

nginix:
    extends: packer-validate
    variables:
        ospath: "$WORKDIR/nginix/" 
    

packer-build:
  stage: deploy

  script:
    - echo "packer build-deploy ... "
    - packer build -force "$WORKDIR/$OS_PATH" build.json

  only:
    - main
    - tags
  when: manual  

mysql:
    extends: packer-build
    variables:
        ospath: "$WORKDIR/mysql/"  

nginix:
    extends: packer-build
    variables:
        ospath: "$WORKDIR/nginix/" 
  