variables:
  workdir: "${CI_PROJECT_DIR}"
  ospath: ""

image:
  name: hashicorp/packer
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

stages:
  - deploy

packer-build:
  stage: deploy

  before_script:
    - echo "packer validate ... "
    - packer validate "$workdir/$ospath" .
  script:
    - echo "packer build-deploy ... "
    - packer build -force "$workdir/$ospath" .

  only:
    - main

mysql:
    extends: packer-build
    variables:
        ospath: "$SCRIPT_PATH/mysql/"  

nginix:
    extends: packer-build
    variables:
        ospath: "$SCRIPT_PATH/nginix/" 

